coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false
        paths:
          - "src"
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  after_n_builds: 1
  show_carryforward_flags: true
ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "dist/**/*"
  - "coverage/**/*"
github_checks:
  annotations: true